[programs.localnet]
clipchain = "DPYRPGR7cLrtYR1E3E3yjhFbfnZk9qQh6eoryvSZiZBY"

[programs.devnet]
clipchain = "DPYRPGR7cLrtYR1E3E3yjhFbfnZk9qQh6eoryvSZiZBY"

[provider]
cluster = "devnet"
wallet = "/home/jjsch/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
solana_version = "1.18.11"
